USE Library;

INSERT INTO Publishers(PublisherName, Website, Email, Phone,
                        PublisherAddress, YearOfFounding)
VALUES
('Bantam Books', 'www.randomhousebooks.com/imprint/bantam-books/',
'N/A', 'N/A', 'New York City, U.S.', '1945'), 
('MIT Press', 'https://mitpress.mit.edu/', 'N/A', 
'617-253-5646', '255 Main Street, 9th Floor, Cambridge, MA 02142', '1962'), 
('Penguin Classics', 'www.penguinclassics.com', 'N/A', 'N/A', 'London, England', '1935'), 
('W. W. Norton & Company', 'https://wwnorton.com/', 'N/A', '(212) 354-5500', 
'W. W. Norton & Company, Inc. 500 Fifth Avenue New York, New York 10110', '1923'),
('Folio Junior', 'https://www.foliojr.com/', 'N/A', '212-400-1494​​', 
'630 9th Avenue, Suite 1009, New York, NY 10036', '1972'), 
('Harper Collins', 'https://harpercollins.co.uk/',
'N/A', 'N/A', '1 Robroyston Gate, Robroyston, Glasgow, G33 1JN', '1987'),
('Disney-Hyperion Books', 'https://books.disney.com/brand/other/disney-hyperion/',
'N/A', 'N/A', 'N/A', '1990'),  
('Scholastic Press', 'https://www.scholastic.co.uk/', 'enquiries@scholastic.co.uk',
'+44 199 389 3474', 'Scholastic Building 557 Broadway, New York City, New York 10012, United States', '1920'),
('Knopf Books', 'https://knopfdoubleday.com/', 'knopfpublicity@penguinrandomhouse.com', 'N/A',
'New York City, U.S.', '1915'),
('Random House', 'https://randomhousebooks.com/', 'N/A', 'N/A', 'Random House Tower, 1745 Broadway, New York City, U.S.',
'1927'),
('Barnes & Noble', 'https://press.barnesandnoble.com/', 'N/A', 'N/A',
'33 East 17th Street, New York, NY 10003', '1931'),
('Harcourt', 'defunct', 'defunct', 'defunct', 'defunct', 'N/A'),
('BookSurge', 'defunct', 'defunct', 'defunct', 'defunct', 'N/A'),
('Cambridge University Press', 'https://www.cambridge.org/gb/universitypress', 'N/A',
'N/A', 'Cambridge, England', '1534'),
('Simon & Schuster', 'https://www.simonandschuster.com/', 'N/A', 'N/A',
'Simon & Schuster Building, Manhattan, New York City, United States', '1924'),
('Prestwick House', 'https://www.prestwickhouse.com/', 'info@prestwickhouse.com', 
'800-932-4593', '58 Artisan Dr. Smyrna, DE 19977', '1983'),
('William Morrow', 'https://www.harpercollins.com/', 'N/A', 'N/A', 'New York City', '1926'),
('Tor Books', 'https://torpublishinggroup.com/imprints/tor-books/', '', '',
'Equitable Building, New York City', '1980'),
('Bloomsbury Arden Shakespeare', 'https://www.bloomsbury.com/uk/discover/bloomsbury-academic/the-arden-shakespeare/', 
'N/A', 'N/A', '50 Bedford Square, London, WC1B 3DP', '1986'),
('Story Line Press', 'https://redhen.org/imprints-and-series/story-line-press/', 
'editorial@redhen.org', '(626) 356-4760', '1540 Lincoln Ave, Pasadena, CA 91103', '1985'),
('Companhia das Letras', 'http://www.companhiadasletras.com.br/', 
'N/A', 'N/A', 'São Paulo', '1986'),
('Ballantine Books', 'https://www.randomhousebooks.com/imprint/ballantine-books/',
'N/A', 'N/A', 'New York City, New York', '1952'),
('Ace', 'https://www.penguin.com/ace-overview/', 'N/A', 'N/A',
'New York City', '1952'),
('Walker Books', 'https://www.walker.co.uk/', 'onlineshop@walker.co.uk', '+44 (0)20 7793 0909', 
'87 Vauxhall Walk, London, SE11 5HJ', '1978'),
('Atria', 'https://www.simonandschusterpublishing.com/atria/', 'N/A', 
'N/A', 'Simon & Schuster Building, New York City', '2002')
